name: matrix
on: workflow_dispatch

jobs:
  list_versions:
    runs-on: ubuntu-latest
    outputs:
      job_versions: ${{ steps.dynamic.outputs.versions }}

    steps:
      - id: dynamic
        run: |
          echo "::set-output name=versions::{\"version\": [\"v1.16\",\"v1.17\", \"v1.18\", \"v1.19\", \"v1.19.1\" ] }"

      # - id: dynamic-include
      #   run: |
      #     echo "::set-output name=versions::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"



  do_work:
    name: processing_${{ matrix.version }}
    needs: list_versions
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2    
      matrix: ${{ fromJSON(needs.list_versions.outputs.job_versions) }}
    steps:
      - run: |
          echo stubber get docstubs ${{ matrix.project }} 
          echo stubber get frozen ${{ matrix.project }} 
          echo stubber get merge ${{ matrix.project }} 
          echo stubber get publish ${{ matrix.project }} 

